Feature/omk 11062&10608
Opmantek/nmis9 pull request #41
Opened 2024-07-12 00:27 UTC by whatgwan

check avx support and added a last daemon start check

2024-07-26 04:25 UTC, markdueck1 requested changes

2024-07-26 04:25 UTC, markdueck1 commented on admin/support.pl
> +                my $status = `systemctl is-active $daemon 2>/dev/null`;
do we need to see if systemctl is available on the box?

2024-07-26 04:25 UTC, markdueck1 commented on admin/support.pl
> +                chomp $status;
this should check to see if $status is something before it starts working with it

2024-08-16 02:48 UTC, whatgwan commented on admin/support.pl
> +                my $status = `systemctl is-active $daemon 2>/dev/null`;
I have added in your suggestion

2024-08-16 02:48 UTC, whatgwan commented on admin/support.pl
> +                chomp $status;
I have added in your suggestion

2024-08-16 03:24 UTC, markdueck1 approved these changes

2024-08-16 03:25 UTC, merged